use my_macros::EnumStr;

#[derive(EnumStr)]
enum Status {
    Pending,
    Active,
    Banned,
}

fn main() {
    // 1. Create a few variants
    let current_status = Status::Active;
    let fallback_status = Status::Pending;

    // 2. Use the .as_str() method generated by our #[derive(EnumStr)]
    println!("--- System Status ---");
    println!("The current user is: {}", current_status.as_str());
    println!("The queue state is:   {}", fallback_status.as_str());

    // 3. You can even use it for comparisons or logic
    if current_status.as_str() == "Active" {
        println!("System is go for launch!");
    }
}