use my_macros::Getters;

#[derive(Getters)]
pub struct Player {
    health: i32,
    name: String,
}

fn main() {
    // 1. Create an instance of our struct
    let p = Player {
        health: 100,
        name: "Rishi".to_string(),
    };

    // 2. Call the methods that were GENERATED by the macro
    // Notice we didn't write 'fn health(&self)' manually!
    println!("--- Player Stats ---");
    println!("Name:   {}", p.name());
    println!("Health: {}", p.health());
    
    // 3. Demonstrate that they are references
    let h: &i32 = p.health(); 
    println!("The value of health is: {}", h);
}